### ISSUE TITLE
Pre-install packages which would otherwise require runtime restart

### ISSUE THREAD

**Issue by keller-mark** [hubmapconsortium/user_workspaces_server#105]
See https://github.com/vitessce/vitessce-python/issues/198 for details.

Pre-pip-install `ipywidgets==7.7.2` in the workspace to allow loading of ipywidgets in workspace notebooks without the need for an extra notebook runtime restart.

Link to more details on slack: https://hubmapconsortium.slack.com/archives/C02UPEGH7PA/p1662472508259989

**Comment by jpuerto-psc** [comment]
Added this to the config files for dev and prod and seems to be functioning after refreshing the page. Mark will look into what needs to be done to avoid the refresh.
