### ISSUE TITLE
Bad URLs should 404

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/user_workspaces_server#25]
By mistake, was POSTing to `https://workspaces-api.dev.hubmapconsortium.org//tokens/`. The response was `{'message': 'Missing Authentication Token'}`. More helpful to respond with a 4xx and appropriate message.

**Comment by jpuerto-psc** [comment]
Django ignores situations where // is passed and interprets it as just / - this was just a token not actually being passed.
