### ISSUE TITLE
Documentation under version control

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/user_workspaces_server#31]
API documentation needs to be under version control.
- https://drive.google.com/file/d/1XbGHwL_HcU4-9J1oiSeIJoRXJuui29oi/view
- https://docs.google.com/document/d/1W6qJkLoKMqxYtB1p7CpAo-XBkUqCMtTLnT9DogpUErc/edit#heading=h.9jkhr47ngjym
- https://docs.google.com/document/d/1h88wz4-PhF5JyozFGMoqyamfR0xDhrUkaxeL4Fcu1Cc/edit#

**Comment by jpuerto-psc** [comment]
REST API Docs:
https://smart-api.info/ui/bf965a56ce398f8b37de68c05b4ef125#/

Additional documentation will have to be brought in at some later time as part of #37 Documentation 2.0 push (Sphinx documentation)
