### ISSUE TITLE
Use static code analysis

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/user_workspaces_server#33]
Static code analysis in CI is a basic software engineering discipline which reduces bugs. For python [flake8](https://flake8.pycqa.org/) is a reasonable choice.

**Comment by jpuerto-psc** [comment]
Added Action for this, see [commit f7da30809713ab1594750204fd7231c029e5a078](https://github.com/hubmapconsortium/user_workspaces_server/commit/f7da30809713ab1594750204fd7231c029e5a078)
