### ISSUE TITLE
Document workspace delete

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/user_workspaces_server#36]
The [diagram](https://drive.google.com/file/d/1XbGHwL_HcU4-9J1oiSeIJoRXJuui29oi/view) has delete but the [doc](https://docs.google.com/document/d/1W6qJkLoKMqxYtB1p7CpAo-XBkUqCMtTLnT9DogpUErc/edit#) doesn't. Not sure how precisely to pass the ID.

**Comment by jpuerto-psc** [comment]
https://smart-api.info/ui/bf965a56ce398f8b37de68c05b4ef125#/
