### ISSUE TITLE
Add workspace_id to jobs GET

### ISSUE THREAD

**Issue by jpuerto-psc** [hubmapconsortium/user_workspaces_server#53]

**Comment by mccalluc** [comment]
If it's not any more difficult on your end, it would actually be slightly more convenient for us to get the job ID  belonging to the workspaces, rather than the other way around, but we can deal with either approach.

**Comment by jpuerto-psc** [comment]
Added workspace_id to Jobs GET and added query params to allow for searching on specific fields.
