### ISSUE TITLE
In Jupyter workspace, Vitessce doesn't always render

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/user_workspaces_server#72]
We don't have a consistent reproducer, but both Juan and I have seen this.
- Instead of getting Vitessce, we just see the repr of the widget (or something like that... I don't understand widget rendering, so I might not be describing it accurately.)
- I first saw this when I selected and evaluated all the cells at once... it would be interesting if this is also true for Juan.
- In the browser console I saw `Exception opening new comm` ... not sure if related
- It might be useful for folks with more experience in widget development to give debugging tips here -- My sense is that it's not a Vitessce problem, but knowing how widgets should work will be helpful in understanding what parts of the Jupyter instance aren't working quite right.
- OTOH: If Vitessce devs have _ever_ seen vitessce fail to render, that would be good to know: It might be a more general problem with Vitessce, and not just this environment.
- There are other quirks in this Jupyter environment: #66. If there is a broader problem with communication between the back and front end, that might be an easier issue to tackle, and might get to the root of the problem, even if the symptoms aren't as annoying -- but this is just a guess.

**Comment by jpuerto-psc** [comment]
@mccalluc - I've had this same experience with Jupyter Notebooks outside of the context of the workspaces. IE, running Jupyter locally or using Open OnDemand on Bridges2. Because of this I don't **believe** that it is an issue with workspaces, but maybe resolving the other Jupyter quirks will take care of this as well.

**Comment by mccalluc** [comment]
Ilan says:
> I think we’ve had old issues with this actually.
>
> Maybe not, I don’t see anything.  But yes, I’ve seen this before and pretty sure it’s been resolved before.

**Comment by ngehlenborg** [comment]
@mccalluc or @jpuerto-psc Can you share the failing Vitessce configs?

**Comment by jpuerto-psc** [comment]
@ngehlenborg not sure if this is what you're looking for...

`conf = VitessceChainableConfig(
    name="HuBMAP Data Portal", description="", schema_version="1.0.4"
).add_dataset(
    uid="A",
    name="Visualization Files",
    files=[
        VitessceConfigDatasetFile(
            data_type="raster",
            file_type="raster.json",
            options={
                "schemaVersion": "0.0.2",
                "usePhysicalSizeScaling": False,
                "images": [
                    {
                        "name": "VAN0005-RK-1-1-AF_preIMS_registered.ome.tif",
                        "type": "ome-tiff",
                        "url": "https://assets.hubmapconsortium.org/a698201644fede089d32d57b1e592753/ometiff-pyramids/processedMicroscopy/VAN0005-RK-1-1-AF_preIMS_images/VAN0005-RK-1-1-AF_preIMS_registered.ome.tif?token=AgoNWydwBxpk5gm87GY9XlE2eV1Wrob2N234oX6aJEpN19VpYOSgCPKjeyB1YYrYpjVwnG5Pwzv27DI9ExrjnTn58D",
                        "metadata": {
                            "omeTiffOffsetsUrl": "https://assets.hubmapconsortium.org/a698201644fede089d32d57b1e592753/output_offsets/processedMicroscopy/VAN0005-RK-1-1-AF_preIMS_images/VAN0005-RK-1-1-AF_preIMS_registered.offsets.json?token=AgoNWydwBxpk5gm87GY9XlE2eV1Wrob2N234oX6aJEpN19VpYOSgCPKjeyB1YYrYpjVwnG5Pwzv27DI9ExrjnTn58D",
                            "isBitmask": False,
                        },
                    }
                ],
            },
        )
    ],
).add_view(
    dataset_uid="A", component="spatial", x=3, y=0, w=9, h=12
).add_view(
    dataset_uid="A", component="description", x=0, y=8, w=3, h=4
).add_view(
    dataset_uid="A",
    component="layerController",
    x=0,
    y=0,
    w=3,
    h=8,
    props={"disable3d": [], "disableChannelsIfRgbDetected": True},
)`

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/68066250/181604827-e08e8470-643c-4abc-b5f3-2777864e6fcc.png">

**Comment by jpuerto-psc** [comment]
As per discussion with Chuck, this issue will be moved else where as it is not unique to workspaces.
